'use strict';
const $=id=>document.getElementById(id),G=AWG,KEY='anime-world-generator-v1';let storageOK=true;
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
let state=read(KEY,null);if(!state||state.version!==1||!G.worlds[state.world]||!Array.isArray(state.queue))state=G.fresh('jjk');
G.upgrade(state);
let prefs=read(KEY+'-prefs',{sound:false,speed:'normal',reactions:'full'}),archive=read(KEY+'-archive',[]),spinning=false,angle=0,audio;
if(state.pending){const savedStep=G.current(state);if(savedStep){const selected=savedStep.options.findIndex(x=>x.label===state.pending.label);if(selected>=0){const total=savedStep.options.reduce((a,x)=>a+x.weight,0),before=savedStep.options.slice(0,selected).reduce((a,x)=>a+x.weight,0);angle=(Math.PI*2-(before+savedStep.options[selected].weight/2)/total*Math.PI*2)%(Math.PI*2);}}}
const chapters=[['Identity','Who are you in this world?'],['Cursed Energy','Your source of power'],['Techniques','What can you do?'],['Physical Stats','Your natural ability'],['Combat & IQ','How you think and fight'],['Final Battle','Your ultimate challenge']];
const colors=['#cf9636','#714bdd','#3d69d1','#138d94','#724bb6','#ad3e77','#35758a','#5851af','#b86935','#39745c','#6b3f9b','#365986'];
// A single wallet record keeps gem purchases and bonus rerolls together.
function wallet(){const w=read(KEY+'-wallet',{});return {gems:Number.isSafeInteger(w.gems)&&w.gems>=0?w.gems:0,bonus:Number.isSafeInteger(w.bonus)&&w.bonus>=0?w.bonus:0,awarded:Array.isArray(w.awarded)?w.awarded.filter(x=>typeof x==='string'):[]}}
function writeWallet(w){try{localStorage.setItem(KEY+'-wallet',JSON.stringify(w));return true}catch{storageOK=false;$('saveStatus').textContent='Could not save gems — please free browser storage and try again';return false}}
function rerollsAvailable(){return state.rerolls+wallet().bonus}
function awardGem(){if(!state.finished||!state.gemEligible||state.results.find(x=>x.id==='win')?.label!=='VICTORY')return false;const w=wallet();if(w.awarded.includes(state.id))return false;w.gems++;w.awarded.push(state.id);return writeWallet(w)}
function renderWallet(){const w=wallet();$('gemShop').textContent='◆ '+w.gems;$('gemShop').setAttribute('aria-label','Gem shop: '+w.gems+' gems');$('gemShop').title='1 gem buys 1 bonus reroll';$('buyReactionReroll').textContent='Buy reroll · 1 gem ('+w.gems+' saved)';$('buyReactionReroll').disabled=spinning||state.finished||w.gems<1}
function buyReroll(){if(spinning)return false;const w=wallet();if(w.gems<1)return false;w.gems--;w.bonus++;if(!writeWallet(w))return false;render();if($('reactionDialog').open)showMobileReaction();return true}
function showGemShop(){const body=openDialog('Gems & bonus rerolls');function paint(message=''){const w=wallet();body.replaceChildren();body.append(text('h3','◆ '+w.gems+' gems'),text('p','Each completed victory earns 1 gem. Spend 1 gem to buy 1 bonus reroll.'),text('p','Saved bonus rerolls: '+w.bonus),text('p','You still start each run with 3 free rerolls. Bonus rerolls carry between runs and are used after your free rerolls. Gems and bonus rerolls are shared across anime on this browser/device.','muted'));const buy=text('button','Buy 1 reroll · 1 gem','primary');buy.disabled=spinning||w.gems<1;buy.onclick=()=>paint(buyReroll()?'Purchased! Your bonus reroll is saved.':'Purchase could not be saved. No gems were spent.');body.append(buy);if(message)body.append(text('p',message,'muted'))}paint()}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(KEY+'-prefs',JSON.stringify(prefs));localStorage.setItem(KEY+'-archive',JSON.stringify(archive));}catch{storageOK=false}$('saveStatus').textContent=storageOK?'✓ Saved on this device':'Storage unavailable — keep this window open';}
function text(tag,content,cls){const e=document.createElement(tag);e.textContent=content;if(cls)e.className=cls;return e}
function beep(freq=500,duration=.06){if(!prefs.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),gain=audio.createGain();o.connect(gain);gain.connect(audio.destination);o.frequency.value=freq;gain.gain.setValueAtTime(.04,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.start();o.stop(audio.currentTime+duration)}catch{}}
function drawWheel(rotation=angle){const cv=$('wheel'),ctx=cv.getContext('2d'),s=G.current(state),list=s?.options||[{label:'Your story continues',weight:1}];const total=list.reduce((a,x)=>a+x.weight,0);ctx.clearRect(0,0,1100,1100);let start=-Math.PI/2+rotation;list.forEach((o,i)=>{const arc=o.weight/total*Math.PI*2;ctx.beginPath();ctx.moveTo(550,550);ctx.arc(550,550,516,start,start+arc);ctx.closePath();const grad=ctx.createRadialGradient(550,550,120,550,550,520);grad.addColorStop(0,'#18223f');grad.addColorStop(1,colors[i%colors.length]);ctx.fillStyle=grad;ctx.fill();ctx.strokeStyle='#10192a';ctx.lineWidth=7;ctx.stroke();ctx.save();ctx.translate(550,550);ctx.rotate(start+arc/2);ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='600 '+(list.length>12?36:41)+'px Segoe UI';if(arc>.12){ctx.translate(365,0);ctx.rotate(Math.PI/2);const words=o.label.split(' ');if(o.label.length>16&&words.length>1){const mid=Math.ceil(words.length/2);ctx.fillText(words.slice(0,mid).join(' '),0,-10,230);ctx.fillText(words.slice(mid).join(' '),0,35,230);}else ctx.fillText(o.label,0,10,250)}ctx.restore();start+=arc;});ctx.beginPath();ctx.arc(550,550,526,0,Math.PI*2);ctx.strokeStyle='#6b578e';ctx.lineWidth=5;ctx.stroke();ctx.beginPath();ctx.arc(550,550,537,0,Math.PI*2);ctx.strokeStyle='#232c44';ctx.lineWidth=8;ctx.stroke();}
function render(){const w=G.worlds[state.world],s=G.current(state);const nav=$('animeTabs'),oldScroll=$('animeTabList')?.scrollLeft||0;nav.replaceChildren();const prev=text('button','‹','anime-arrow'),next=text('button','›','anime-arrow'),list=text('div','','anime-tab-list');list.id='animeTabList';list.setAttribute('role','group');list.setAttribute('aria-label','Anime worlds');prev.setAttribute('aria-label','Scroll anime left');next.setAttribute('aria-label','Scroll anime right');for(const [key,v] of Object.entries(G.worlds)){const b=text('button',v.name,key===state.world?'active':'');b.setAttribute('aria-pressed',String(key===state.world));b.disabled=spinning;b.onclick=()=>{if(key!==state.world)confirmNew(key)};list.append(b)}prev.onclick=()=>list.scrollBy({left:-240,behavior:'smooth'});next.onclick=()=>list.scrollBy({left:240,behavior:'smooth'});nav.append(prev,list,next);list.scrollLeft=oldScroll;AWGPortrait.render($('buildPortrait'),state);$('appearanceSetup').hidden=spinning||state.results.length>0||!!state.pending||state.finished;$('genderChoice').value=state.genderChoice||'male';$('genderResolved').textContent=state.genderChoice==='random'?'Selected: '+state.gender:'';
$('progressText').textContent=state.finished?'Run complete':`Spin ${state.index+1} / ${state.queue.length}`;$('progressBar').style.width=(state.finished?100:state.index/state.queue.length*100)+'%';$('chapters').replaceChildren();chapters.forEach(([name,desc],i)=>{if(i===1)name=w.energy;const div=text('div','','chapter '+(state.finished||i<(s?.chapter??6)?'done':i===s?.chapter?'current':''));div.append(text('i',state.finished||i<(s?.chapter??6)?'✓':String(i+1).padStart(2,'0')));const c=text('div','');c.append(text('strong',name),text('small',desc));div.append(c);$('chapters').append(div)});
renderWallet();$('rerollsLeft').textContent='↻  '+rerollsAvailable()+' rerolls left';$('worldName').textContent=w.name;$('identity').textContent=state.results.find(x=>x.id==='origin')?.label||'Unknown protagonist';$('stepLabel').textContent=state.finished?'YOUR STORY IS COMPLETE':s.ability?'DISCOVER YOUR NEXT POWER':chapters[s.chapter][0].toUpperCase();$('question').textContent=state.finished?'Your legend is written.':s.label;$('context').textContent=state.finished?'Save your character or begin another life.':s.id.startsWith('mastery')?(state.results.find(x=>x.id==='ability'+s.id.replace('mastery',''))?.label||''):(s.chapter===2?w.name+' • Powers & mastery':'Every spin shapes your story.');
$('result').textContent=state.pending?.label||(state.finished?state.results.at(-1)?.label:'YOUR DESTINY AWAITS');$('resultTag').textContent=state.pending?'RESULT REVEALED':state.finished?'RUN COMPLETE':'SPIN TO DISCOVER';$('spin').textContent=state.finished?'VIEW CHARACTER':state.pending?'CONTINUE':'SPIN THE WHEEL';$('spin').disabled=spinning;$('reroll').disabled=spinning||!state.pending||rerollsAvailable()<=0||state.finished;$('reroll').textContent='↻  Reroll · '+rerollsAvailable()+' left';$('newRun').disabled=spinning;
renderIdentity();$('buildRows').replaceChildren();$('buildRows').className='build-rows';if(!state.results.length)$('buildRows').append(text('p','Your identity, abilities, and stats will appear here.','muted'));state.results.filter(x=>!['age','clan','faction','field'].includes(x.id)).slice(-2).forEach(r=>{const row=text('div','','build-row');row.append(text('span',r.name),text('strong',r.label));$('buildRows').append(row)});$('buildRows').scrollTop=$('buildRows').scrollHeight;
$('statStrip').replaceChildren();['strength','speed','durability','battle iq'].forEach(id=>{const r=state.results.find(x=>x.id===id);$('statStrip').append(text('span',id.replace(/\b\w/g,c=>c.toUpperCase())+'  '+(r?.label||'—')))});
$('battleHint').textContent=s?.id==='win'?`Victory chance: ${G.chance(state)}% · Based on your build, enemy and preparation.`:'';$('sound').textContent=prefs.sound?'♫':'♪';$('sound').setAttribute('aria-pressed',String(prefs.sound));document.querySelector('.verdict').hidden=prefs.reactions==='off';showReaction(state.reaction||{frame:8,tag:'NEW STORY',text:'Your origin story is one spin away.'},false);if(s?.id==='exactAge')$('context').textContent='Age range: '+s.ageRange+' · Every year has an equal chance.';if(state.pending&&s?.id==='exactAge')$('result').textContent=state.pending.label+' YEARS OLD';drawWheel();save();}
function setReactionFrame(art,world,frame){const boundaries=world==='hxh'?[0,335,710,1086]:world==='fairytail'?[0,358,710,1086]:[0,362,724,1086];const row=Math.floor(frame/4),top=boundaries[row],height=boundaries[row+1]-top;art.style.backgroundSize='400% '+(1086/height*100)+'%';art.style.backgroundPosition=(frame%4/3*100)+'% '+(top/(1086-height)*100)+'%';}
function showReaction(r,animate=true){renderCameo(r,false);const frame=r.frame??(r.tile===4?8:r.tile===5?9:r.tile),pair=G.reactionPairs[state.world];$('reactionText').textContent=r.text;$('reactionTag').textContent=r.tag;$('reactionSpeaker').textContent=r.speaker||(frame>=8?pair.join(' & '):pair[Math.floor(frame/4)]);$('reactionImage').style.backgroundImage=`url('reactions-${state.world}.png')`;setReactionFrame($('reactionImage'),state.world,frame);applySpeakerArt($('reactionImage'),r);$('reactionImage').setAttribute('aria-label',$('reactionSpeaker').textContent+' — '+r.tag.toLowerCase());if(animate&&prefs.reactions==='full'){const card=document.querySelector('.verdict');card.classList.remove('pop');void card.offsetWidth;card.classList.add('pop')}}
function spin(reroll=false){if(spinning||state.finished)return;const s=G.current(state);if(reroll){if(!state.pending||rerollsAvailable()<1)return;if(state.rerolls>0)state.rerolls--;else{const w=wallet();if(w.bonus<1)return;w.bonus--;if(!writeWallet(w))return;}}const idx=G.weighted(s.options),choice=s.options[idx];const sum=s.options.reduce((a,o)=>a+o.weight,0),before=s.options.slice(0,idx).reduce((a,o)=>a+o.weight,0),middle=(before+choice.weight/2)/sum*Math.PI*2;const target=(Math.PI*2-middle)%(Math.PI*2);const from=angle,to=angle+Math.PI*2*5+((target-angle%(Math.PI*2)+Math.PI*2)%(Math.PI*2));const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const duration=reduced?50:prefs.speed==='fast'?800:3500;spinning=true;state.pending=null;render();$('result').textContent='FATE IS DECIDING…';let start,lastTick=0;function frame(t){start??=t;const p=Math.min((t-start)/duration,1);angle=from+(to-from)*(1-Math.pow(1-p,4));drawWheel();if(t-lastTick>100+p*230){beep(270+Math.random()*170);lastTick=t}if(p<1)requestAnimationFrame(frame);else{spinning=false;angle=target;state.pending={...choice};state.reaction=G.reaction(state,s,choice);render();showReaction(state.reaction);showMobileReaction();beep(state.reaction.benefit==='bad'?220:state.reaction.benefit==='good'?740:440,.25)}}requestAnimationFrame(frame)}
let tutorialActive=false,tutorialOpening=false;
function showTutorial(){tutorialOpening=true;if($('dialog').open)$('dialog').close();tutorialActive=true;let page=0;const slides=[['Welcome to Anime World Generator','Build an anime character one spin at a time. Swipe or scroll the anime row at the top, or use its arrows, to choose a world.'],['Choose your character','Before your first spin, choose Male, Female, or Random. Your complete character illustration has a consistent face and outfit across poses. Your sheet records your age, equipment, and powers.'],['Spin, react, then Continue','Read the question, spin the wheel, and enjoy the reaction. Continue locks in your result. Use a reroll before Continue if you want another chance; you get three free per run. Each completed victory earns one gem; the ◆ shop sells one bonus reroll for one gem. Unused bonus rerolls carry over. View wheel odds shows the actual chances.'],['Try Auto-spin','Turn on Auto-spin in Settings and close Settings to start. Each reaction shows its question and waits for Continue before the next spin. Turn it off for manual play.'],['Follow your build','Identity icons summarize your origin, age, roots, and faction. Full sheet shows every result. On phones, use Wheel, Character, and Reactions to switch panels.'],['Your final battle and saved characters','Your stats and the enemy affect victory odds. The final scene features your selected opponent. Completed builds save in My Characters, where you can view, download, or delete them. Saves stay in this browser. Replay this guide from Settings.']];function paint(){const body=openTutorialBody();body.append(text('p','Step '+(page+1)+' of '+slides.length,'muted'),text('h3',slides[page][0]),text('p',slides[page][1]));const actions=text('div','','tutorial-actions'),skip=text('button','Skip tutorial'),back=text('button','Back'),next=text('button',page===slides.length-1?'Let’s play':'Next','primary');back.disabled=page===0;skip.onclick=()=>finish();back.onclick=()=>{page--;paint()};next.onclick=()=>{if(page===slides.length-1)finish();else{page++;paint()}};actions.append(skip,back,next);body.append(actions)}function openTutorialBody(){if(!$('dialog').open)return openDialog('How to play');$('dialogTitle').textContent='How to play';$('dialogBody').replaceChildren();return $('dialogBody')}function finish(){tutorialActive=false;prefs.tutorialSeen=true;save();$('dialog').close()}paint();tutorialOpening=false}
function identityIcon(r){if(['age','exactAge','ancientAge'].includes(r.id))return '⌛';if(r.id==='potential')return '✦';if(r.id==='clan')return '🌳';if(r.id==='faction')return /villain|curse user|phantom/i.test(r.label)?'☠':'⚑';return /sorcerer|mage|spirit/i.test(r.label)?'✧':/pirate/i.test(r.label)?'☠':/assassin|shinobi|ninja/i.test(r.label)?'⚔':/titan|dragon|saiyan/i.test(r.label)?'🔥':/hero/i.test(r.label)?'★':'🛡'}
function renderIdentity(){const box=$('identityBadges');box.replaceChildren();state.results.filter(r=>r.chapter===0&&(!['age','ancientAge'].includes(r.id)||!state.results.some(x=>x.id==='exactAge'))).forEach(r=>{const badge=text('span',identityIcon(r)+' '+r.label,'identity-badge');badge.title=r.name+': '+r.label;box.append(badge)})}
function autoSpin(){if(!tutorialOpening&&!tutorialActive&&prefs.autoSpin==='on'&&!spinning&&!state.pending&&!state.finished&&!$('dialog').open&&!$('reactionDialog').open){setPanel('wheel');spin()}}
$('spin').onclick=()=>{if(spinning)return;if(state.finished){showCharacter(state);return}if(state.pending){G.commit(state);angle=0;if(state.finished){state.gemEligible=true;save();awardGem();archive=archive.filter(x=>x.id!==state.id);archive.unshift(JSON.parse(JSON.stringify(state)));archive=archive.slice(0,50);}render();if(state.finished)showCharacter(state);else autoSpin();return}spin()};$('reroll').onclick=()=>spin(true);
function openDialog(title){$('dialogTitle').textContent=title;$('dialogBody').replaceChildren();$('dialog').showModal();return $('dialogBody')}$('closeDialog').onclick=()=>$('dialog').close();
function confirmNew(world){const start=()=>{state=G.fresh(world,prefs.appearance||state.genderChoice||'male');angle=0;$('reactionText').textContent='Your origin story is one spin away.';$('reactionTag').textContent='NEW STORY';$('reactionImage').style.backgroundPosition='50% 0';render();autoSpin()};if(!state.results.length&&!state.pending||state.finished){start();return}const body=openDialog('Start a new run?');body.append(text('p','Your current unfinished run will be replaced. Completed characters stay in My Characters.'));const b=text('button','Start '+G.worlds[world].name,'primary');b.onclick=()=>{$('dialog').close();start()};body.append(b)}$('newRun').onclick=()=>confirmNew(state.world);
$('sound').onclick=()=>{prefs.sound=!prefs.sound;render();beep()};$('settings').onclick=()=>{const body=openDialog('Game settings');[['Auto-spin','autoSpin',[['off','Off'],['on','On — Continue starts the next spin']]],['Spin speed','speed',[['normal','Dramatic'],['fast','Quick']]],['Meme reactions','reactions',[['full','Full Chaos'],['light','Light'],['off','Off']]]].forEach(([label,key,values])=>{const row=text('label','','setting');row.append(text('span',label));const select=document.createElement('select');values.forEach(([value,label])=>{const op=text('option',label);op.value=value;select.append(op)});select.value=prefs[key]||'off';select.onchange=()=>{prefs[key]=select.value;render()};row.append(select);body.append(row)});const tutorial=text('button','Replay tutorial','subtle');tutorial.onclick=()=>showTutorial();body.append(tutorial);body.append(text('p','Progress saves automatically in this browser. This fan-made game uses its own balance rules.','muted'))};
function download(run){const lines=['ANIME WORLD GENERATOR',G.worlds[run.world].name,'Appearance: '+(run.gender||'male'),'',...run.results.map(r=>r.name+': '+r.label)];const blob=new Blob([lines.join('\n')],{type:'text/plain'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Anime-World-'+run.world+'-'+run.id+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function showStats(run){if($('dialog').open)$('dialog').close();const body=openDialog(G.worlds[run.world].name+' character');const tabs=text('div','','sheet-tabs'),grid=text('div','','summary-grid'),pager=text('div','','sheet-pager');let category=0,page=0;const buttons=[];function paint(){buttons.forEach((b,i)=>{b.className=i===category?'active':'';b.setAttribute('aria-pressed',String(i===category))});const rows=run.results.filter(r=>r.chapter===category);grid.replaceChildren();rows.slice(page*6,page*6+6).forEach(r=>{const item=text('div','','summary-item');item.append(text('span',r.name),text('strong',r.id==='exactAge'?r.label+' years old':r.label));grid.append(item)});if(!rows.length)grid.append(text('p','No results in this chapter yet.','muted'));pager.replaceChildren();const prev=text('button','Previous'),next=text('button','Next');prev.disabled=page===0;next.disabled=(page+1)*6>=rows.length;prev.onclick=()=>{page--;paint()};next.onclick=()=>{page++;paint()};pager.append(prev,text('span',`Page ${page+1} / ${Math.max(1,Math.ceil(rows.length/6))}`),next)}chapters.forEach(([label],i)=>{const b=text('button',i===1?G.worlds[run.world].energy:label);b.onclick=()=>{category=i;page=0;paint()};tabs.append(b);buttons.push(b)});if(AWGBattle.describe(run)){const back=text('button','Final battle scene','subtle');back.onclick=()=>showCharacter(run);body.append(back)}const portraitLink=text('button','View illustrated portrait','subtle');portraitLink.onclick=()=>showPortrait(run,()=>showCharacter(run));body.append(portraitLink,tabs,grid,pager);paint();const b=text('button','Download character','primary');b.style.marginTop='16px';b.onclick=()=>download(run);body.append(b)}
$('characterSheet').onclick=()=>showCharacter(state);
$('viewOdds').onclick=()=>{const s=G.current(state),body=openDialog('Wheel odds');if(!s){body.append(text('p','Your run is complete.'));return}const sum=s.options.reduce((a,x)=>a+x.weight,0);let page=0;const grid=text('div','','summary-grid'),pager=text('div','','sheet-pager');function paint(){grid.replaceChildren();s.options.slice(page*8,page*8+8).forEach(o=>{const row=text('div','','summary-item');row.append(text('span',o.label),text('strong',(o.weight/sum*100).toFixed(1)+'%'));grid.append(row)});pager.replaceChildren();const prev=text('button','Previous'),next=text('button','Next');prev.disabled=page===0;next.disabled=(page+1)*8>=s.options.length;prev.onclick=()=>{page--;paint()};next.onclick=()=>{page++;paint()};pager.append(prev,text('span',`Page ${page+1} / ${Math.ceil(s.options.length/8)}`),next)}body.append(grid,pager);paint()};
function setPanel(panel){document.body.dataset.panel=panel;['Wheel','Build','Reactions'].forEach(name=>$('show'+name).setAttribute('aria-pressed',String(panel===name.toLowerCase())))}
function applySpeakerArt(el,r){
 el.classList.remove('enemy-reaction','new-speaker');el.style.aspectRatio='';
 if(r.enemySpeaker&&r.enemyIndex>=0){
  const atlas=AWGBattleArt[state.world],rect=atlas.frames[r.enemyIndex];
  if(rect){const [x,y,w,h]=rect;el.style.backgroundImage=`url('battle-enemies-${state.world}.png')`;el.style.backgroundSize=`${atlas.width/w*100}% ${atlas.height/h*100}%`;el.style.backgroundPosition=`${x/(atlas.width-w)*100}% ${y/(atlas.height-h)*100}%`;el.style.aspectRatio=w+'/'+h;el.classList.add('enemy-reaction');}
 }else if(Number.isInteger(r.portraitIndex)){
  el.style.backgroundImage="url('reaction-cast-v2.png')";el.style.backgroundSize='600% 300%';el.style.backgroundPosition=`${r.portraitIndex%6*20}% ${Math.floor(r.portraitIndex/6)*50}%`;el.style.aspectRatio='3/4';el.classList.add('new-speaker');
 }
}
let reactionWaiting=false;
function renderCameo(r,mobile){
 const guest=$(mobile?'mobileZoro':'zoroGuest'),exchange=$(mobile?'mobileCameo':'cameoExchange'),stage=$(mobile?'mobileStage':'verdictStage');
 guest.hidden=!r.cameo;exchange.hidden=!r.cameo;stage.className='reaction-stage'+(r.cameo?' has-cameo':'');
 exchange.textContent=r.cameo?`Lost Zoro: “${r.cameo.guestLine}”\n${r.cameo.host}: “${r.cameo.hostLine}”`:'';
}
function showMobileReaction(){
 if((!matchMedia('(max-width: 900px)').matches&&prefs.autoSpin!=='on')||prefs.reactions==='off'||!state.pending||spinning)return;
 // Do not interrupt a settings or character-sheet dialog opened during the spin.
 if($('dialog').open){reactionWaiting=true;return}
 reactionWaiting=false;
 renderCameo(state.reaction,true);
 $('mobileTopic').textContent=G.current(state)?.label||'Your result';
 $('mobileResult').textContent=$('result').textContent;
 $('mobileTag').textContent=$('reactionTag').textContent;
 $('mobileSpeaker').textContent=$('reactionSpeaker').textContent;
 $('mobileCaption').textContent=$('reactionText').textContent;
 $('mobileArt').style.backgroundImage=$('reactionImage').style.backgroundImage;
 $('mobileArt').style.backgroundPosition=$('reactionImage').style.backgroundPosition;
 $('mobileArt').style.backgroundSize=$('reactionImage').style.backgroundSize;
 applySpeakerArt($('mobileArt'),state.reaction);
 $('mobileArt').setAttribute('aria-label',$('reactionSpeaker').textContent+' reaction');
 $('rerollReaction').textContent='Reroll · '+rerollsAvailable()+' left';
 $('rerollReaction').disabled=rerollsAvailable()<=0;
 if(!$('reactionDialog').open)$('reactionDialog').showModal();
}
$('closeReaction').onclick=()=>{$('reactionDialog').close();setPanel('wheel')};
$('reactionDialog').oncancel=()=>setPanel('wheel');
$('continueReaction').onclick=()=>{if(spinning||!state.pending)return;$('reactionDialog').close();setPanel('wheel');$('spin').click()};
$('rerollReaction').onclick=()=>{if(spinning||!state.pending||rerollsAvailable()<=0)return;$('reactionDialog').close();setPanel('wheel');spin(true)};
$('dialog').onclose=()=>{if(tutorialActive){tutorialActive=false;prefs.tutorialSeen=true;save()}if(reactionWaiting){reactionWaiting=false;showMobileReaction()}autoSpin()};
$('showWheel').onclick=()=>setPanel('wheel');$('showBuild').onclick=()=>setPanel('build');$('showReactions').onclick=()=>setPanel('reactions');

function showPortrait(run,back){if($('dialog').open)$('dialog').close();const body=openDialog('Your illustrated character');const view=text('div','','portrait-view'),picture=text('div','','portrait-large'),art=text('div','','portrait-art'),details=text('div','','portrait-details');picture.append(art);const p=AWGPortrait.render(art,run);const facts=[p.gender==='female'?'Female build':'Male build',p.origin,'Age: '+p.age,p.faction,p.weapon?'Equipment: '+p.weapon:'Equipment: waiting for your roll',p.abilities.length?'Powers: '+p.abilities.join(', '):'Powers: waiting for your rolls'];if(p.transformed)facts.push('Form: '+p.transformed);facts.forEach(f=>details.append(text('p',f)));details.append(text('p',(p.preview?'Previewing the current roll. ':'')+'Complete full-body illustration with a consistent face, outfit and pose. Outfit and anatomy represent your anime world; exact age, equipment and abilities remain on your character sheet.','portrait-note'));view.append(picture,details);body.append(view);if(back){const b=text('button','Back','subtle');b.onclick=back;body.append(b)}}
$('portraitButton').onclick=()=>showPortrait(state);
$('genderChoice').onchange=()=>{if(spinning||state.results.length||state.pending||state.finished)return;G.setAppearance(state,$('genderChoice').value);prefs.appearance=state.genderChoice;render()};
function showCharacter(run){if(!AWGBattle.describe(run)){showStats(run);return}if($('dialog').open)$('dialog').close();const body=openDialog('Your final battle');const scene=text('div','','battle-scene');const d=AWGBattle.render(scene,run);const details=text('p',d.enemy+' · '+d.condition+' · '+d.field,'battle-details');const actions=text('div','','final-actions');const sheet=text('button','Character stats','primary');sheet.onclick=()=>showStats(run);const portrait=text('button','Clean portrait');portrait.onclick=()=>showPortrait(run,()=>showCharacter(run));const downloadButton=text('button','Download build');downloadButton.onclick=()=>download(run);actions.append(sheet,portrait,downloadButton);body.append(scene,details);if(run.gemEligible&&run.results.find(x=>x.id==='win')?.label==='VICTORY')body.append(text('p',wallet().awarded.includes(run.id)?'◆ Victory reward: 1 gem earned. Your gems are saved in the Gem shop.':'Your victory gem could not be saved. Reopen the game after freeing browser storage to retry.','gem-reward'));body.append(actions);}

function showLibrary(){if($('dialog').open)$('dialog').close();const body=openDialog('My Characters');if(!archive.length){body.append(text('p','Finish a run to save your first character. Your current run is autosaved separately.','muted'));return}archive.forEach(run=>{const card=text('article','','saved-card'),art=text('div','','saved-art'),picture=text('div','','portrait-art');art.append(picture);AWGPortrait.render(picture,run,false);card.append(art,text('h3',run.results.find(x=>x.id==='origin')?.label||'Protagonist'),text('p',G.worlds[run.world].name+' · '+run.results.at(-1)?.label));const actions=text('div','','saved-actions'),b=text('button','View build');b.onclick=()=>showCharacter(run);const d=text('button','Download');d.onclick=()=>download(run);const p=text('button','Portrait');p.onclick=()=>showPortrait(run,showLibrary);const del=text('button','Delete','danger');del.setAttribute('aria-label','Delete '+(run.results.find(x=>x.id==='origin')?.label||'character')+' from '+G.worlds[run.world].name);del.onclick=()=>confirmDelete(run);actions.append(b,p,d,del);card.append(actions);body.append(card)})}
function confirmDelete(run){$('dialog').close();const body=openDialog('Delete this character?');body.append(text('p',(run.results.find(x=>x.id==='origin')?.label||'This character')+' · '+G.worlds[run.world].name),text('p','This removes this saved character from My Characters on this device. Your current run stays intact. This cannot be undone.'));const row=text('div','','delete-actions'),cancel=text('button','Keep character'),remove=text('button','Delete character','danger');cancel.onclick=showLibrary;remove.onclick=()=>{const updated=archive.filter(x=>x.id!==run.id);try{localStorage.setItem(KEY+'-archive',JSON.stringify(updated));archive=updated;showLibrary()}catch{body.append(text('p','Could not save the deletion. Your character has been kept.','muted'));remove.disabled=true}};row.append(cancel,remove);body.append(row)}
$('library').onclick=showLibrary;
$('gemShop').onclick=showGemShop;
$('buyReactionReroll').onclick=()=>{if(!buyReroll())$('mobileTag').textContent='Could not save purchase';};
window.addEventListener?.('storage',e=>{if(e.key===KEY+'-wallet'){render();if($('reactionDialog').open)showMobileReaction()}});
awardGem();
render();
if(!prefs.tutorialSeen)showTutorial();else autoSpin();
