(function(root){
'use strict';
const tiers=[['Beginner',18,1],['Below average',15,2],['Average',25,3],['Skilled',21,4],['Expert',13,5],['Mastered',6,6],['Transcendent',2,7]];
const power=[['Very low',7,1],['Low',15,2],['Average',30,3],['High',26,4],['Exceptional',14,5],['Monstrous',6,6],['Legendary',2,7]];
const yes=[['No',60,2],['Yes',40,6]];
const reactionPairs={jjk:['Yuji','Gojo'],naruto:['Naruto','Sasuke'],onepiece:['Luffy','Zoro'],bleach:['Ichigo','Rukia'],dragonball:['Goku','Vegeta']};
const worlds={
 jjk:{name:'Jujutsu Kaisen',energy:'Cursed energy',ability:'Cursed technique',origin:['Sorcerer','Cursed spirit','Curse user','Reincarnated sorcerer','The Honored One'],clans:['Zenin','Kamo','Gojo','Independent'],groups:['Tokyo Jujutsu High','Kyoto Jujutsu High','Independent','Curse user alliance'],powers:['Limitless','Blood Manipulation','Ten Shadows','Cursed Speech','Boogie Woogie','Ratio Technique','Projection Sorcery','Straw Doll Technique','Construction','Disaster Flames','Ice Formation','Star Rage','Copy','Idle Transfiguration','Comedian','Private Pure Love Train'],enemies:['Yuji','Megumi','Todo','Jogo','Mahito','Toji','Yuta','Kenjaku','Gojo','Sukuna'],extras:[['Reverse Cursed Technique','bool'],['RCT mastery','master','Reverse Cursed Technique'],['Heal others','bool','Reverse Cursed Technique'],['Domain Expansion','bool'],['Domain refinement','master','Domain Expansion'],['Anti-domain skill','list',['None','Simple Domain','Hollow Wicker Basket','Falling Blossom Emotion']],['Black Flash proficiency','master']],weapons:['Cursed katana','Playful Cloud','Split Soul Katana','Inverted Spear of Heaven','Chain of a Thousand Miles']},
 naruto:{name:'Naruto',energy:'Chakra',ability:'Signature jutsu',origin:['Shinobi','Rogue ninja','Samurai','Jinchuriki','Reincarnated prodigy'],clans:['Uchiha','Hyuga','Uzumaki','Senju','Nara','Akimichi','Yamanaka','Independent'],groups:['Hidden Leaf','Hidden Sand','Hidden Mist','Hidden Cloud','Hidden Stone'],powers:['Shadow Clone','Rasengan','Chidori','Fireball Jutsu','Flying Raijin','Sand Manipulation','Puppet Technique','Shadow Possession','Water Dragon','Eight Trigrams','Wood Release','Lightning Armor','Summoning Jutsu','Mind Transfer'],enemies:['Rock Lee','Neji','Gaara','Kakashi','Orochimaru','Itachi','Pain','Obito','Madara','Naruto'],extras:[['Chakra nature','list',['Fire','Wind','Lightning','Earth','Water']],['Genjutsu mastery','master'],['Taijutsu mastery','master'],['Sage Mode','bool'],['Sage mastery','master','Sage Mode'],['Sealing mastery','master'],['Summoning pact','list',['None','Toads','Snakes','Slugs','Hawks','Dogs']]],weapons:['Chakra blade','Giant fan','Samehada','Kunai set','Executioner blade']},
 onepiece:{name:'One Piece',energy:'Willpower',ability:'Signature move',origin:['Human','Fish-man','Mink','Giant','Lunarian'],clans:['East Blue','West Blue','North Blue','South Blue','Grand Line','New World'],groups:['Pirates','Marines','Revolutionary Army','Bounty hunters','Independent'],powers:['Flying Slash','Fish-man Karate','Rokushiki','Electro','Dragon Claw','Flame Kick','Impact Strike','Sonic Shot','Giant Spear','Counter Stance','Pressure Cannon','Whirlwind Cut'],enemies:['Buggy','Arlong','Crocodile','Rob Lucci','Doflamingo','Katakuri','Zoro','Kizaru','Kaido','Shanks'],extras:[['Devil Fruit','list',['None','Flame-Flame','Ice-Ice','Op-Op','Gum-Gum','Tremor-Tremor','Flower-Flower','Leopard Zoan']],['Fruit mastery','master','Devil Fruit'],['Armament Haki','bool'],['Armament mastery','master','Armament Haki'],['Observation Haki','bool'],['Observation mastery','master','Observation Haki'],['Conqueror’s Haki','bool'],['Conqueror mastery','master','Conqueror’s Haki']],weapons:['Katana','Three swords','Rifle','Staff','Kanabo','Cutlass']},
 bleach:{name:'Bleach',energy:'Spiritual pressure',ability:'Spiritual technique',origin:['Soul Reaper','Quincy','Arrancar','Fullbringer','Visored'],clans:['Rukongai','Seireitei','Karakura Town','Hueco Mundo','Wandenreich'],groups:['Gotei 13','Independent','Royal Guard allies','Hueco Mundo faction'],powers:['Getsuga Tensho','Cero','Kido Barrage','Spirit Arrow','Flash Step Strike','Soul Chain','Flame Slash','Ice Prison','Shadow Bind','Petal Storm','Lightning Spear','Spirit Shield'],enemies:['Renji','Ikkaku','Grimmjow','Byakuya','Ulquiorra','Kenpachi','Shunsui','Aizen','Ichigo','Yhwach'],extras:[['Release unlocked','bool'],['Release mastery','master','Release unlocked'],['Ultimate release','bool'],['Ultimate mastery','master','Ultimate release'],['Movement mastery','master'],['Barrier mastery','master'],['Spiritual sensing','master']],weapons:['Zanpakuto','Spirit bow','Twin blades','Lance','Fullbring focus']},
 dragonball:{name:'Dragon Ball',energy:'Ki',ability:'Signature technique',origin:['Human','Saiyan','Namekian','Android','Frost demon','Majin'],clans:['Earth','Planet Vegeta','Namek','Other World','Unknown planet'],groups:['Z Fighters','Galactic Patrol','Independent','Frieza Force'],powers:['Kamehameha','Galick Gun','Special Beam Cannon','Destructo Disc','Solar Flare','Instant Transmission','Final Flash','Death Beam','Spirit Bomb','Tri-Beam','Masenko','Energy Barrier'],enemies:['Yamcha','Tien','Piccolo','Android 18','Frieza','Cell','Majin Buu','Vegeta','Goku','Beerus'],extras:[['Transformation potential','bool'],['Transformation mastery','master','Transformation potential'],['Ki sensing','master'],['Flight mastery','master'],['Regeneration','bool'],['Divine training','bool'],['Divine control','master','Divine training']],weapons:['Power Pole','Sword','Energy blade','Weighted gear','Battle armor']}
};
const extra=typeof module!=='undefined'?require('./worlds-extra.js'):root.AWGExtra;
Object.assign(worlds,extra.worlds);Object.assign(reactionPairs,extra.pairs);
const variety=typeof module!=='undefined'?require('./reaction-variety.js'):root.AWGReactionVariety;
for(const [world,names] of Object.entries(variety.additions))reactionPairs[world].push(...names);
worlds.naruto.enemies.splice(7,0,'Sasuke');worlds.onepiece.enemies.splice(8,0,'Luffy');worlds.bleach.enemies.splice(2,0,'Rukia');
const options=list=>list.map((x,i)=>typeof x==='string'?{label:x,weight:1,score:3}:{label:x[0],weight:x[1],score:x[2]});
function step(id,label,chapter,list,extra={}){return{id,label,chapter,options:options(list),...extra};}
function ageFollowups(range){
 if(range==='Ancient')return [step('ancientAge','How ancient are you?',0,['100–119','200–219','500–519','1000–1019'],{name:'Ancient age range',neutral:true})];
 const [low,high]=range.split(/[–-]/).map(Number);
 if(!Number.isInteger(low)||!Number.isInteger(high)||high<low||high-low>100)return [];
 return [step('exactAge','Your exact age?',0,Array.from({length:high-low+1},(_,i)=>String(low+i)),{name:'Exact age',neutral:true,ageRange:range})];
}
function upgrade(state){
 if(!['male','female'].includes(state.gender)){state.gender='male';state.genderChoice='male';}
 if(state.finished||state.queue.some(x=>x.id==='exactAge'||x.id==='ancientAge'))return state;
 const age=state.results.find(x=>x.id==='age');
 if(age)state.queue.splice(state.index+(state.pending?1:0),0,...ageFollowups(age.label));
 return state;
}
function makeQueue(key){const w=worlds[key];return[
step('origin','Who are you?',0,w.origin.map((x,i)=>[x,i===w.origin.length-1?5:24,i===w.origin.length-1?6:3]),{name:'Identity'}),step('age','How old are you?',0,['16–20','21–30','31–45','46–70','Ancient'],{neutral:true}),step('clan',key==='naruto'?'Your clan':'Your roots',0,w.clans,{neutral:true}),step('faction','Who do you stand with?',0,w.groups,{neutral:true}),step('potential','Your natural potential',0,power),
step('energy',w.energy+' reserves',1,power),step('control',w.energy+' control',1,tiers),step('output',w.energy+' output',1,power),step('recovery',w.energy+' recovery',1,tiers),
step('count','How many '+(w.ability.toLowerCase().endsWith('y')?w.ability.toLowerCase().slice(0,-1)+'ies':w.ability.toLowerCase()+'s')+'?',2,[['1',40,3],['2',35,4],['3',18,5],['4',6,6],['5',1,7]]),
...w.extras.map((e,i)=>step('extra'+i,e[0],2,e[1]==='bool'?yes:e[1]==='master'?tiers:e[2],{requires:e[3]||(typeof e[2]==='string'?e[2]:null),neutral:e[1]==='list'})),
...['Strength','Durability','Speed','Stamina','Reflexes'].map(x=>step(x.toLowerCase(),x,3,power)),
...['Combat skill','Weapon skill','IQ','Battle IQ'].map(x=>step(x.toLowerCase(),x,4,tiers)),step('tool','Your equipment',4,w.weapons,{neutral:true}),step('toolmaster','Equipment mastery',4,tiers),
step('enemy','Who is your enemy?',5,w.enemies.map((x,i)=>[x,1,Math.min(7,2+i*.55)]),{neutral:true}),step('enemyLevel','Your enemy’s condition',5,[['Weakened',25,2],['Base form',43,3],['Full power',25,5],['Prime',7,7]],{neutral:true}),step('field','The battlefield',5,['City ruins','Open plains','Dense forest','Underground arena','Mountain summit'],{neutral:true}),step('advantage','Your starting conditions',5,[['Ambushed',20,1],['Exhausted',15,2],['Even footing',40,3],['Prepared',20,5],['Perfect setup',5,7]]),step('win','Do you win?',5,[['VICTORY',50,7],['DEFEAT',50,1]])];}
function setAppearance(run,choice,rng=Math.random){run.genderChoice=['male','female','random'].includes(choice)?choice:'male';run.gender=run.genderChoice==='random'?(rng()<.5?'male':'female'):run.genderChoice;return run;}
function fresh(world,gender='male',rng=Math.random){return setAppearance({version:1,id:Date.now()+'-'+Math.random().toString(36).slice(2),world,queue:makeQueue(world),index:0,results:[],pending:null,rerolls:3,finished:false},gender,rng);}
function weighted(list,r=Math.random()){let sum=list.reduce((s,x)=>s+x.weight,0),target=r*sum;for(let i=0;i<list.length;i++){target-=list[i].weight;if(target<0)return i;}return list.length-1;}
function chance(state){const values=state.results.filter(x=>!x.neutral&&x.id!=='count'&&x.id!=='advantage');const avg=values.reduce((s,x)=>s+x.score,0)/(values.length||1);const enemy=state.results.find(x=>x.id==='enemy')?.score||3;const level=state.results.find(x=>x.id==='enemyLevel')?.score||3;const setup=state.results.find(x=>x.id==='advantage')?.score||3;return Math.max(5,Math.min(95,Math.round(55+(avg-enemy)*13+(3-level)*5+(setup-3)*5)));}
function current(state){const s=state.queue[state.index];if(!s)return null;if(s.id==='win'){const p=chance(state);return{...s,options:options([['VICTORY',p,7],['DEFEAT',100-p,1]])};}return s;}
function commit(state){const s=current(state);if(!s||!state.pending)return;const result={id:s.id,name:s.name||s.label,label:state.pending.label,score:state.pending.score,chapter:s.chapter,neutral:s.neutral||false};state.results.push(result);if(s.id==='age'||s.id==='ancientAge')state.queue.splice(state.index+1,0,...ageFollowups(result.label));if(s.id==='count'){const n=Number(result.label),w=worlds[state.world];const inserted=[];for(let i=1;i<=n;i++){inserted.push(step('ability'+i,w.ability+' '+i,2,w.powers,{neutral:true,ability:true}),step('mastery'+i,'Technique '+i+' mastery',2,tiers));}state.queue.splice(state.index+1,0,...inserted);}state.index++;state.pending=null;
while(state.queue[state.index]?.requires){const required=state.queue[state.index].requires;const r=state.results.find(x=>x.name===required);if(r&&r.label!=='No'&&r.label!=='None')break;state.index++;}
const next=state.queue[state.index];if(next?.ability){const used=state.results.filter(x=>x.id.startsWith('ability')).map(x=>x.label);next.options=next.options.filter(x=>!used.includes(x.label));}if(state.index>=state.queue.length)state.finished=true;}
const dialogue=typeof module!=='undefined'?require('./reactions.js'):root.AWGDialogue;
function reaction(state,s,r,rng){return dialogue.react(state,s,r,reactionPairs,rng);}
root.AWG={worlds,tiers,reactionPairs,ageFollowups,upgrade,makeQueue,fresh,setAppearance,weighted,current,commit,chance,reaction};if(typeof module!=='undefined')module.exports=root.AWG;
})(typeof window!=='undefined'?window:globalThis);
