(function(root){
'use strict';
const additions={jjk:['Nobara','Nanami'],naruto:['Sakura','Kakashi'],onepiece:['Nami','Sanji'],bleach:['Renji','Urahara'],dragonball:['Piccolo','Bulma'],fairytail:['Gray','Erza'],mha:['Todoroki','Uraraka'],aot:['Levi','Armin'],hxh:['Kurapika','Leorio']};
// Original fan dialogue. Each voice has its own vocabulary and priorities.
const signatures={
Yuji:['I want everyone to make it home.','Let’s work on it together.','I am not leaving anyone behind.'],Gojo:['Your spectacular teacher has a suggestion.','Try looking at it from another angle.','I expect an interesting demonstration.'],Naruto:['I earned my place by refusing to quit.','The village needs people who keep their word.','Ramen after training; no skipping training.'],Sasuke:['Watch the opening before you move.','Precision decides the exchange.','Do not waste motion proving a point.'],Luffy:['Can we try it on our next adventure?','My crew comes first.','I want to see what happens when you really try!'],Zoro:['Discipline keeps your blade steady.','One more set before you rest.','Pick your target and commit.'],Ichigo:['There are people counting on us.','I need a plan that gets everyone back.','Draw your weapon when you know why you are fighting.'],Rukia:['Footwork first; dramatic speeches later.','I can draw the formation if that helps.','Soul Society has seen stranger things.'],Goku:['I want to test that in a spar!','A new training challenge sounds great.','Let’s build up to it without wrecking the planet.'],Vegeta:['A prince does not coast on yesterday’s strength.','Your next opponent will not applaud your potential.','Show me discipline worthy of that power.'],Natsu:['I am fired up for the next mission!','Nobody hurts our guild and walks away.','Let’s train until we can break through!'],Lucy:['My spirits deserve a sensible plan.','That is going in my next chapter.','Please leave enough money for repairs.'],Deku:['I need to write down the activation conditions.','There could be a rescue application here.','A small adjustment might reduce the recoil.'],Bakugo:['Quit wasting motion and finish the drill.','I am still taking first place.','Aim before you blast the entire training ground.'],Eren:['We need a path beyond these walls.','Anger alone will not keep the squad alive.','I refuse to waste the opening we fought for.'],Mikasa:['Check your anchors and cover the flank.','Everyone needs to return from this mission.','Keep your movements controlled.'],Gon:['Can you show me how that works?','I want to try training with you!','Killua probably spotted something I missed.'],Killua:['Keep one trick hidden from your opponent.','I already checked the exits.','Gon would rush in; let’s think first.'],
Nobara:['I refuse to win without looking good doing it.','A nail in the right place beats a flashy speech.','Do not mistake confidence for careless aim.'],Nanami:['Overtime is avoidable with proper preparation.','Find the weak point and make one clean strike.','A responsible sorcerer accounts for the cost.'],Sakura:['Control matters more than brute force.','I would rather prevent an injury than heal one.','You should see what one precise punch can do.'],Kakashi:['Try reading the opponent before reading your own hype.','Protect the team before chasing a personal win.','I have a little experience with copied techniques.'],Nami:['How much will this plan cost us?','Watch the weather before you pick a route.','We are keeping an escape route and the treasure.'],Sanji:['Nobody fights well on an empty stomach.','My kicks can handle the frontline.','A good plan leaves time to feed the crew.'],Renji:['I did not train Zabimaru for a timid swing.','Closing the gap takes more than shouting.','I want another shot at that training drill.'],Urahara:['My shop may have just the training tool you need.','A clever preparation can look like a lucky accident.','Let’s test the theory before the expensive part.'],Piccolo:['Quiet your mind and sense the opening.','I expect you at training before sunrise.','Keep your guard up after the first exchange.'],Bulma:['Let me measure it before you blow up my equipment.','I can build support gear if you give me actual numbers.','Science needs data, not another crater.'],Gray:['Ice-Make rewards a clear shape and a steady mind.','Natsu would charge in; I would set the trap first.','Give me a second to freeze the approach.'],Erza:['A guild member finishes the training they started.','Choose armor for the opponent, not for applause.','We protect our friends through discipline.'],Todoroki:['Balance both sides before increasing output.','Temperature control is part of the fight.','I would test the transition between attacks.'],Uraraka:['Think about how it helps a rescue.','Weight and momentum can change the whole plan.','Let’s practice landing safely before going higher.'],Levi:['Clean your gear before trusting it with your life.','One precise cut is enough when you have the opening.','Panic wastes gas and gets people killed.'],Armin:['We should compare the routes before committing.','An overlooked detail can change our entire plan.','Let me work out what the opponent expects.'],Kurapika:['Conditions matter as much as raw aura.','Never make a vow you do not understand.','I will not trade judgment for revenge.'],Leorio:['I am bringing a medical kit whether you like it or not.','Surviving the exam matters more than showing off.','A decent doctor asks what it will cost your body.']};
const voices={};
for(const [name,lines] of Object.entries(signatures))voices[name]={bad:lines.map(x=>'There is a weakness to fix. '+x),good:lines.map(x=>'That gives us something to work with. '+x),neutral:lines};
const extraLines={
Nobara:[['That aim needs work. I am not wasting nails on excuses.','You call that a finish? Get up; we have another drill.'],['Now that has style and impact. I approve.','Keep that timing. You might actually match my confidence.'],['Would a hammer strike create an opening for it?','I want to see the technique, not hear its sales pitch.']],
Nanami:[['This risk was foreseeable. Adjust the plan.','You are spending energy without securing an advantage.'],['Efficient. Repeat that without increasing the cost.','A sound result. Keep the execution consistent.'],['We should establish the working limits first.','Account for the recovery time in your plan.']],
Sakura:[['That recoil could injure you. Reduce the output first.','Your control is slipping. Back to the chakra drill.'],['That precision is exactly what we trained for.','Good. You can protect someone with that strength.'],['Does it need fine control or a sudden burst?','Let’s assess how much recovery you will need.']],
Kakashi:[['You showed your opening before your attack.','A rescue plan would be useful right about now.'],['You kept your teammate covered. That matters.','A well-timed feint. I might put down my book for this.'],['What would you do if the opponent read that move?','Try it with a partner watching your blind spot.']],
Nami:[['We cannot afford to replace the entire ship.','Those odds call for an exit route, immediately.'],['Excellent. Now we can keep the treasure and our lives.','That could get us through the storm in one piece.'],['Does the weather affect its range?','I am adding that to our route calculations.']],
Sanji:[['You need rest and a proper meal before trying again.','Do not leave the crew exposed while you show off.'],['A clean finish. Dinner is on the way.','That opening leaves room for a combination kick.'],['How much energy does it burn? I will plan the meal.','Can you cover the crew while I handle the close fight?']],
Renji:[['You are leaving too much space between attacks.','Zabimaru would catch that hesitation. Train the follow-up.'],['Now you are fighting like you mean it.','That reach could make a nasty combination with my blade.'],['Let’s test it at more than one distance.','I want to see how you recover after the first swing.']],
Urahara:[['An instructive failure. The test equipment disagrees.','That weakness calls for a very specific training exercise.'],['How promising. I have a more difficult test prepared.','A clever result; perhaps we can make it even cheaper.'],['Shall we try a controlled experiment?','I wonder which assumption the opponent will make about it.']],
Piccolo:[['You lost focus as soon as the pressure increased.','Stop increasing output before you can hold your guard.'],['Good control. Keep it when you are tired.','You sensed the opening before you moved. Keep that habit.'],['How long can you maintain that without losing focus?','We will test it against a moving target.']],
Bulma:[['That reading is terrible. Shut it down before it breaks.','I am putting a shield around the next experiment.'],['Those measurements are much better than expected.','Finally, usable data! I can work with that.'],['Give me the range, duration, and energy cost.','Do you need a sensor or just better protective gear?']],
Gray:[['You left a gap wide enough for Natsu to notice.','A rushed shape will crack under pressure.'],['A clean opening. I can freeze their retreat.','That is the kind of control a team can count on.'],['Would a wall of ice change the approach?','We should test it before the next guild mission.']],
Erza:[['Repeat the drill until you can hold your stance.','You have strength; now learn to protect the person beside you.'],['Well executed. The guild can rely on that.','That earns confidence, provided you keep training.'],['Which equipment would let you use it safely?','Prepare a second approach in case the first is blocked.']],
Todoroki:[['You are overcommitting before you control the transition.','That recovery leaves the opposite side exposed.'],['The transition was smooth. Keep that balance.','That gives us a useful way to control the field.'],['How does it behave when the temperature changes?','Would you lead with defense or a fast opening attack?']],
Uraraka:[['Please practice the landing before another launch.','That recoil could put the rescue team in danger.'],['Nice! That could move someone out of danger quickly.','You kept control of the momentum. Great job.'],['Could we use it to move debris safely?','Let’s find out how weight changes the timing.']],
Levi:[['You wasted an opening. Fix it before the next mission.','Loose equipment and sloppy movement. Neither is acceptable.'],['Clean execution. Keep moving.','You finished without exposing the squad. Good.'],['Check the approach and the escape route.','How much gas does that maneuver cost?']],
Armin:[['The plan depends on an opening we cannot guarantee.','We need an alternative before anyone commits.'],['That gives us a route we did not have before.','Good. We can build a coordinated plan around that.'],['What would the enemy expect us to do next?','Let’s compare what we gain against what we expose.']],
Kurapika:[['A poorly understood condition can become a fatal trap.','You are letting emotion decide the risk. Step back.'],['A precise result. Keep your conditions clear.','That control gives you a chance to choose the exchange.'],['What restriction makes the ability stronger?','We should establish exactly when it can fail.']],
Leorio:[['You are paying for that mistake with your body.','No, we are not skipping recovery to try again.'],['You finished in one piece. That is worth celebrating.','Good work. Save some stamina for the people who need help.'],['What symptoms show up after you use it?','I want a plan that includes getting everyone treated.']]
};
for(const [name,lists] of Object.entries(extraLines))['bad','good','neutral'].forEach((mood,i)=>voices[name][mood].push(...lists[i]));
const enemyTraits={
jjk:['close-range cursed-energy strikes','Ten Shadows summons','Boogie Woogie swaps','volcanic cursed flames','soul-changing contact','ambushes and cursed tools','copied techniques','schemes and cursed spirits','Limitless defenses','relentless cutting attacks'],
naruto:['taijutsu pressure','precise chakra-point strikes','sand defenses','feints and copied jutsu','snakes and forbidden techniques','genjutsu traps','coordinated Paths','Sharingan counters','space-time attacks','battlefield control','shadow-clone combinations'],
onepiece:['tricky split-body attacks','fish-man strength','sand and dehydration','Rokushiki speed','strings controlling the arena','Observation Haki counters','three-sword pressure','light-speed approaches','unpredictable rubber attacks','heavy club strikes','overwhelming Haki'],
bleach:['Zabimaru’s reach','close-range spear attacks','ice-based openings','destructive close-range attacks','petal-blade coverage','long-range spiritual attacks','overwhelming sword pressure','deceptive game-like rules','hypnosis and manipulation','rapid sword combinations','control over future possibilities'],
dragonball:['fast martial-arts rushes','precise energy attacks','tactical ki pressure','efficient android attacks','cruel ranged ki attacks','adaptable combinations','unpredictable regeneration','explosive ki counters','martial-arts adaptability','destruction energy'],
fairytail:['sky magic and support','Ice-Make traps','celestial-spirit teamwork','iron-enhanced attacks','Requip versatility','fire-dragon pressure','lightning bursts','celestial-body magic','dangerous dark magic','devastating dragon power'],
mha:['sticky restraints','Engine-powered rushes','gravity and momentum','hardened close-range strikes','ice and fire coverage','One For All movement','explosive mobility','wide-ranging blue flames','decay spreading through contact','multiple quirk combinations'],
aot:['a dangerous Titan approach','unpredictable Titan movement','coordinated armed soldiers','a coordinated Warrior formation','fast jaws and claws','precise ODM attacks','armored Titan defenses','Attack Titan pressure','long-range thrown projectiles','heat and enormous reach'],
hxh:['deception before the fight','explosive Nen traps','Jajanken commitments','electric speed','aura-debt pressure','swift sword attacks','Bungee Gum traps','stolen Nen abilities','overwhelming aura and speed','adaptation and enormous aura']};
const portraits=Object.values(additions).flat();
const expressionNames=['Crying','Thoughtful','Approving','Celebrating'];
const expressionAtlases=[1,2,3].map(group=>({file:'reaction-expressions-'+group+'.png',width:1536,height:1024,columns:[0,256,512,768,1024,1280,1536],rows:[0,256,512,768,1024]}));
function portraitStyle(index,expression=1){const a=expressionAtlases[Math.floor(index/6)];if(!a||!Number.isInteger(index)||index<0||index>=portraits.length)return null;const col=index%6,row=Number.isInteger(expression)?Math.max(0,Math.min(3,expression)):1,x=a.columns[col],y=a.rows[row],w=a.columns[col+1]-x,h=a.rows[row+1]-y;return {backgroundImage: "url('"+a.file+"')",backgroundSize:(a.width/w*100)+'% '+(a.height/h*100)+'%',backgroundPosition:(x/(a.width-w)*100)+'% '+(y/(a.height-h)*100)+'%',aspectRatio:w+'/'+h};}
root.AWGReactionVariety={additions,voices,signatures,enemyTraits,portraits,expressionNames,expressionAtlases,portraitStyle};
if(typeof module!=='undefined')module.exports=root.AWGReactionVariety;
})(typeof window!=='undefined'?window:globalThis);
