(function(root){
'use strict';
// Original fan dialogue, not quotations from the shows. Ratings describe the player's benefit.
const voices={
Yuji:{bad:['Okay. Nobody panic. Especially me.','We can fix this with training. A lot of training.','I was hoping for something less life-threatening.','Please tell me there is a tutorial for this.'],good:['Now that is something we can use to protect people!','Nice! I would absolutely want you on my team.','Look at you! That training is paying off.','That is a serious upgrade. Let’s put it to good use.'],neutral:['I want to see what you do with that.','That makes your story a little more interesting.','I’m listening. What happens next?','Hey, everybody starts somewhere.']},
Gojo:{bad:['Good thing you have an excellent teacher. Me.','That is adorable. Concerning, but adorable.','We may need to extend your training indefinitely.','I would laugh, but I should probably prepare a lesson.'],good:['Careful. Keep improving and I might have competition.','Not bad. Obviously I make it look easier.','Now you are giving me something interesting to teach.','A promising student! Try not to let it go to your head.'],neutral:['Interesting. I have several very annoying ideas for that.','I could make that work. Your results may vary.','That should make the next lesson entertaining.','Let’s see whether you have the imagination to use it.']},
Naruto:{bad:['Don’t give up! We train again tomorrow!','Believe me, looking hopeless is not the end of the story.','Okay, that one hurt. Ramen first, training next.','You need a comeback arc. I can help with that.'],good:['That’s what I’m talking about!','You are going to make your whole village proud!','Now we’re getting somewhere. Don’t waste it!','I knew you had something big in you!'],neutral:['Your story is just getting started!','I’m not judging. My own start was pretty messy.','What matters is what you choose to do next.','Come on, show me how you make that your own.']},
Sasuke:{bad:['Hmph. More training. Less celebrating.','You cannot intimidate anyone with potential alone.','That weakness will cost you if you ignore it.','I suggest you stop posing and start practicing.'],good:['Not bad. Try to keep up.','Finally. A result worth taking seriously.','That might actually force me to pay attention.','Useful. Don’t mistake it for a guarantee.'],neutral:['I will judge it when I see you use it.','A name on a character sheet proves nothing.','Interesting. Keep your intentions clear.','We will see whether it suits you.']},
Luffy:{bad:['Let’s eat first. Then try again!','That looks difficult. Want me to punch it?','You are not quitting over one bad spin!','Okay! We need food and a really good plan.'],good:['That’s awesome! You’re coming with us!','Show me again! That was so cool!','We are definitely having a feast after this!','Now that looks like an adventure!'],neutral:['Can you do something funny with it?','Sounds interesting! Let’s go find out!','I don’t really get it, but I like your attitude.','As long as you are free to choose your own path!']},
Zoro:{bad:['You lost the fight before I lost the directions.','Stop making excuses. Pick up the weight.','I’ve seen training dummies put up more resistance.','That needs work. Preferably before the next fight.'],good:['Good. Now make it count.','That is worth testing against a real opponent.','Keep that up and we might have a proper spar.','Useful. Just don’t get comfortable.'],neutral:['Does it help in a fight? Then I’ll listen.','Wake me when you are ready to test it.','I care more about discipline than labels.','Fine. Pick a direction and commit to it.']},
Ichigo:{bad:['Okay. We’ve got some work to do.','I’m not letting you walk into a fight like that.','Please stop treating danger like a personality trait.','You need practice, not another dramatic entrance.'],good:['That’s a power worth protecting people with.','Good. Now you can actually back someone up.','I would feel better with you watching my back.','That should make the next fight less one-sided.'],neutral:['As long as you know who you are fighting for.','I didn’t exactly choose a normal life either.','Another complication. Sure. Why not?','Make it your own. That part matters.']},
Rukia:{bad:['Back to the basics. Pay attention this time.','I should draw you a training diagram. A very simple one.','Your enthusiasm is getting ahead of your ability.','That is not a strategy. That is a rescue mission.'],good:['Your training is finally showing.','Good. I might not have to explain this twice.','You have earned a little confidence. Only a little.','That is promising. Keep your composure.'],neutral:['I will explain the important part with a drawing.','Unusual, but not beyond training.','Do not confuse an interesting origin with experience.','We should assess this before you improvise.']},
Goku:{bad:['You just need a stronger training partner!','That is a rough start. Let’s practice together.','Maybe we should warm up before the dangerous part.','Even I think we need a little more preparation.'],good:['Wow! I want to fight you now!','That looks strong! How much further can you take it?','You’ve got me excited for our next spar!','Great! Now let’s see what happens after more training.'],neutral:['I wonder how strong you could get with that.','Interesting! Can you show me how it works?','I’ve met all kinds of fighters. Surprise me!','Sounds like a good reason to train somewhere new.']},
Vegeta:{bad:['Pathetic. Start training.','You call that preparation?','Your confidence is doing work your power cannot.','I refuse to lose because you skipped the basics.'],good:['Finally, a power worth acknowledging.','Do not let one good result make you insufferable.','Acceptable. You still have a long way to go.','Hmph. Perhaps this will not be a complete waste of time.'],neutral:['I will reserve judgment until you demonstrate it.','Your ancestry does not earn my respect. Your training might.','Another unusual fighter. Try to be useful.','I have no interest in your title. Show me your discipline.']}
};
const contexts={
enemyBad:['{enemy} at {value}? That is THEIR advantage, not yours.','The opponent gets {value}. Your odds just took a hit.','I would not cheer for {value} on the enemy’s side.','{value} means {enemy} is more dangerous. Prepare accordingly.'],
enemyGood:['{enemy} is {value}. Take the opening, but stay alert.','A {value} opponent gives you breathing room. Use it.','{value} helps your chances. It does not make you invincible.','Better to face {enemy} like this than at their best.'],
enemyNeutral:['{enemy} in {value}. Don’t assume that means harmless.','{value} is the baseline. We still need a plan for {enemy}.','No extra enemy boost this time. Keep your guard up.','{enemy} is starting in {value}. Let’s see how your build compares.'],
enemy:['You drew {value}. I would study their weaknesses first.','{value} is your opponent. This just got personal.','Against {value}, your build needs more than a dramatic name.','So we are fighting {value}. Let’s make the preparation count.'],
age:['{value} years old. Plenty of story left to write.','At {value}, I would invest in training before posing.','{value}? I am more interested in what you have learned.','Age: {value}. Experience is a separate wheel, apparently.'],
range:['{value}. We still need your exact age before judging the backstory.','An age range of {value}? Let’s narrow that down.','{value}. The birthday reveal gets its own dramatic episode.','Somewhere in {value}. Even the narrator needs more details.'],
ability:['{value}. I want to see the mastery roll before celebrating.','With {value}, creativity could matter as much as raw strength.','You have {value}. Now earn the right to make it look effortless.','{value} is a tool, not an automatic victory. Learn its limits.'],
mastery:['{ability}, but only {value} mastery? Read the manual.','You unlocked {ability} before learning the controls. Classic.','{value} with {ability}. We are doing supervised practice.','That {ability} needs training, not a victory speech.'],
leak:['Huge reserves, {value} control. Full tank, massive leak.','All that energy and {value} control? Stop wasting it.','You have enough energy. What you need is an instruction manual.','Power without control is making your own life harder.'],
iq:['Strong arms, {value} IQ. Please let somebody else plan.','Your muscles are carrying the strategy meeting.','That strength needs a better plan than “hit it again.”','We have the muscle. Now we need someone to read the map.'],
win:['You won. Now tell me you learned something.','Victory! That build actually held together.','You survived the final fight. Enjoy the ending.','The enemy is down. You earned a moment to breathe.'],
loss:['All those spins, and the enemy gets the final speech.','Defeat. Keep the lesson and try another life.','The build had a story. Unfortunately, this was its ending.','We are calling that a very expensive training session.'],
neutral:['{label}: {value}. Let’s see what you make of it.','You got {value}. That adds a new wrinkle to your story.','{value} is part of your build now. The next choice matters.','The wheel picked {value}. Your decisions give it meaning.'],
stat:['{label}: {value}.','You rolled {value} for {label}.','Your {label} came out {value}.','So, {value} {label}.']
};
const specials={
frieza:{Goku:['That Frieza connection looks familiar. Please leave the planet intact.','You remind me of Frieza. I’m hoping the personality is optional.','Frieza-related powers? Let’s use them for sparring, not conquering.','Another fighter with Frieza’s kind of power. This could be interesting.'],Vegeta:['Wonderful. Another Frieza. One was irritating enough.','If you start giving orders like Frieza, this partnership is over.','Frieza’s power without his attitude would be an improvement.','I spent enough time dealing with Frieza. Do not make this nostalgic.']},
limitless:{Yuji:['Limitless? Gojo is going to make this about himself.','You got Limitless. Please tell me the training comes included.','That is Gojo-level homework. I would take notes.','Limitless sounds great. Learning it sounds exhausting.'],Gojo:['Limitless? Excellent taste. The skill is sold separately.','You picked my specialty. I expect very impressive homework.','Another Limitless user? Finally, someone to understand my explanations.','The technique is familiar. Let’s see whether the talent follows.']},
uchiha:{Naruto:['An Uchiha? Great. Please communicate more than Sasuke does.','That clan comes with serious talent. Try smiling occasionally.','Another Uchiha! I’m scheduling friendship and training.','Uchiha, huh? I’m expecting big things and very short conversations.'],Sasuke:['An Uchiha name is a responsibility, not a shortcut.','You carry that clan name. Do something worthy of it.','Being an Uchiha does not excuse poor training.','Another Uchiha. Keep your focus and your own judgment.']},
gum:{Luffy:['That fruit sounds familiar! Show me what you can stretch!','You got my kind of power! Let’s do something ridiculous with it.','Stretchy powers? We are definitely having fun now.','That fruit needs imagination. Fortunately, weird ideas are free.'],Zoro:['Great. More stretching. Try not to launch me anywhere.','Another rubber fighter. The ship is going to suffer.','I already train around one stretchy idiot. Be the careful one.','That fruit is useful. Just keep the experiments away from my nap.']}
};
const cameoLines={
jjk:[['Which way to the ship?','Gojo','You crossed into another anime and still won’t ask for directions?'],['This school isn’t on my map.','Yuji','Who is this guy, and why does he have three swords?'],['I was following the road.','Gojo','That road crossed a franchise boundary. Impressive.'],['Is the captain here?','Yuji','Wrong team. Wrong school. Possibly wrong universe.']],
naruto:[['This isn’t Wano?','Naruto','Who are you? And how did you get into the village?'],['I took a shortcut.','Sasuke','Through another universe? Your navigation needs work.'],['Which way to the port?','Naruto','We’re a hidden village, not a pirate harbor!'],['The road was straight.','Sasuke','Apparently the dimensions were not.']],
bleach:[['Is this the way back to the ship?','Ichigo','Who is this swordsman? How do you get lost into the afterlife?'],['Nice swords. Wrong harbor, though.','Rukia','Harbor? This is Soul Society. Who let you in?'],['I followed the guy in black.','Ichigo','That describes half the people here!'],['Do you have a map?','Rukia','I can draw one. Will you actually follow it?']],
dragonball:[['This isn’t Wano?','Vegeta','Who let this swordsman onto our planet?'],['Where is the ship?','Goku','Which ship? Wait, how did you even get here?'],['I took the left turn.','Vegeta','You took a turn out of your own universe.'],['I’m looking for a blond cook.','Goku','I know some blond fighters, but I wouldn’t ask them to cook.']]
};
function pick(state,key,list,rng){state.dialogueHistory??=[];let choices=list.map((line,i)=>({line,id:key+':'+i})).filter(x=>!state.dialogueHistory.includes(x.id));if(!choices.length){const last=state.dialogueHistory.filter(x=>x.startsWith(key+':')).at(-1);state.dialogueHistory=state.dialogueHistory.filter(x=>!x.startsWith(key+':'));choices=list.map((line,i)=>({line,id:key+':'+i})).filter(x=>list.length===1||x.id!==last);}const choice=choices[Math.floor(rng()*choices.length)%choices.length];state.dialogueHistory.push(choice.id);state.dialogueHistory=state.dialogueHistory.slice(-40);return choice.line;}
function react(state,s,r,pairs,rng=Math.random){
 const pair=pairs[state.world],turn=state.reactionCount||0,speaker=pair[turn%2];state.reactionCount=turn+1;
 const enemy=state.results.find(x=>x.id==='enemy')?.label||'your enemy';
 let score=r.score,kind=s.neutral?'neutral':'stat',tag='',frame;
 if(s.id==='enemyLevel'){score=r.label==='Weakened'?5:r.label==='Base form'?3:1;kind=score<3?'enemyBad':score>3?'enemyGood':'enemyNeutral';tag=score<3?'ENEMY ADVANTAGE':score>3?'OPENING FOR YOU':'STAY ALERT';}
 else if(s.id==='enemy'){score=r.score>=4?2:3;kind='enemy';tag=r.score>=4?'DANGEROUS OPPONENT':'OPPONENT REVEALED';}
 else if(s.id==='win'){kind=r.label==='VICTORY'?'win':'loss';frame=r.label==='VICTORY'?10:11;tag=r.label==='VICTORY'?'VICTORY':'DEFEAT';}
 else if(s.id==='exactAge')kind='age';else if(['age','ancientAge'].includes(s.id))kind='range';
 else if(s.id.startsWith('ability'))kind='ability';
 else if(s.id.startsWith('mastery')&&score<=2){kind='mastery';frame=9;}
 else if(s.id==='control'&&score<=2&&(state.results.find(x=>x.id==='energy')?.score||0)>=5){kind='leak';frame=9;}
 else if(s.id==='iq'&&score<=2&&(state.results.find(x=>x.id==='strength')?.score||0)>=4)kind='iq';
 const neutral=['neutral','age','range','ability','enemyNeutral'].includes(kind);
 const mood=neutral?'neutral':score<=2?'bad':score>=4?'good':'neutral';
 if(frame===undefined)frame=!neutral&&score>=6?8:turn%2*4+(mood==='bad'?(score<=1?0:1):mood==='good'?3:2);
 tag=tag||(neutral?'LORE UNLOCKED':score>=6?'MAIN CHARACTER ENERGY':score>=4?'LET THEM COOK':score<=2?'TRAINING ARC NEEDED':'WE TAKE THOSE');
 const ability=state.results.find(x=>x.id==='ability'+s.id.replace('mastery',''))?.label||'that technique';
 const vars={value:r.label,label:s.label||s.id,enemy,ability};
 let line=pick(state,kind,contexts[kind],rng).replace(/\{(\w+)\}/g,(_,k)=>vars[k]);
 const value=r.label.toLowerCase();let special=value.includes('frieza')||value.includes('frost demon')?'frieza':value.includes('limitless')?'limitless':value.includes('uchiha')?'uchiha':value.includes('gum-gum')?'gum':null;
 if(special&&specials[special][speaker])line+=' '+pick(state,special+speaker,specials[special][speaker],rng);
 else if(kind==='enemyBad'&&speaker==='Goku')line+=' '+pick(state,'gokuDanger',['I’m excited for the challenge, but your odds are worse.','I want a good fight too, but we should prepare first.','That sounds exciting to me. It is still bad news for your chances.','Even a fun challenge needs a plan.'],rng);
 else line+=' '+pick(state,speaker+mood,voices[speaker][mood],rng);
 const result={tile:frame>=8?(frame===9?5:4):frame%4,frame,tag,speaker,text:line,benefit:s.id==='enemyLevel'?(score<3?'bad':score>3?'good':'neutral'):mood};
 // Cosmetic only: the cameo never changes a roll, score, or combat odds.
 const eligible=s.id!=='win'&&state.world!=='onepiece'&&turn>=2&&turn-(state.lastZoroCameo??-100)>=8;
 if(eligible&&rng()<.05){const exchange=pick(state,'cameo'+state.world,cameoLines[state.world].filter(x=>x[1]===speaker),rng);state.lastZoroCameo=turn;result.cameo={guest:'Zoro',host:exchange[1],guestLine:exchange[0],hostLine:exchange[2]};result.frame=pair.indexOf(exchange[1])*4+1;result.speaker=exchange[1];}
 return result;
}
root.AWGDialogue={react};if(typeof module!=='undefined')module.exports=root.AWGDialogue;
})(typeof window!=='undefined'?window:globalThis);
