(function(root){
'use strict';
const voices={
Natsu:{bad:['That is rough. We train until it stops being rough!','I was ready to charge in. Maybe we should bring backup.','Lucy is giving me that look. Apparently we need a plan.','Nobody touches our friends. We will find a way through this.'],good:['Now we are fired up! Let me see it in action!','That kind of power belongs on a job with us!','We are taking the tough mission after this!','Nice! Save some energy for a spar with me!'],neutral:['Can it handle a dragon slayer’s training?','I want to try it out. Lucy wants to read the instructions.','If you stand by your friends, I will stand by you.','Sounds like the start of a great guild mission!']},
Lucy:{bad:['The repair bill is already giving me a headache.','Can we discuss a plan before Natsu breaks something?','That is concerning. My spirits deserve better preparation.','I am adding medical supplies to the mission budget.'],good:['Now that is worth writing into the story!','Good! A clever use of that could save everyone.','Finally, something that makes this job less terrifying.','I like those odds. Let’s still keep an escape route.'],neutral:['There is a story behind that. I want to hear it.','Power is a partnership, not permission to be reckless.','Let me think about how that fits the mission.','Interesting. I should make a note before Natsu gets distracted.']},
Deku:{bad:['There must be a safer way to use that. Let me take notes.','That weakness matters. We need a workaround before anyone gets hurt.','I have made the mistake of pushing too hard. Please pace yourself.','The rescue plan needs an alternative. We can build one.'],good:['That opens up so many combinations! Where is my notebook?','With control like that, you could save a lot of people.','Amazing! The timing and follow-through could be incredible.','That is promising. Let’s practice until it is reliable.'],neutral:['What is the activation condition? And the drawback?','I have about twelve questions about how that works.','Your choices matter more than the label on your quirk.','A small detail could change the whole strategy.']},
Bakugo:{bad:['Quit posing! Your training is nowhere near finished.','That gap in your defense is practically an invitation.','You expect to win with that? Get back to work.','I am not carrying you because you skipped practice.'],good:['Finally! Something I can actually compete with.','Decent. Celebrate after you can do it under pressure.','Keep up. I am still taking the top spot.','That has power. Now prove you can aim it.'],neutral:['Stop explaining your potential and show me results.','A flashy name will not win the match.','I already saw the opening. Did you?','Fine. Figure out how to use it without getting in my way.']},
Eren:{bad:['Then we train harder. I am not accepting a cage as our future.','That weakness can cost lives beyond your own.','If we rush this, somebody else pays for it.','Being angry will not make that shortcoming disappear.'],good:['That brings us one step closer to getting out alive.','Good. Now use it to open a path for everyone.','Power means nothing if we cannot act when it matters.','For once, we have something to push back with.'],neutral:['What will you do when the way forward is blocked?','I care about what we can change with it.','Another part of the world I still need to understand.','Decide why you are fighting before you draw a blade.']},
Mikasa:{bad:['Stay close. We need to cover that weakness.','Check your equipment. Confidence will not stop a blade.','Do not make your squad rescue you unnecessarily.','Retreat is useful when it keeps people alive.'],good:['Good. Keep your movements precise.','I can trust you to hold that position.','Use it carefully. Everyone still needs to return.','That creates an opening. Do not waste it.'],neutral:['Stay aware of the people beside you.','We should test it before relying on it.','Your next decision matters more than your background.','I will watch the flank. Focus on your task.']},
Gon:{bad:['Let’s try again! I want to figure out what went wrong.','Killua is making that face. We should probably listen.','I cannot pretend that is safe. We need more practice.','There has to be another way to approach this!'],good:['That is amazing! Can you show me how you did it?','Now I really want to train with you!','You worked for that. Let’s see how far it can go!','I bet we could make a great combination attack!'],neutral:['I want to understand how it feels to use that.','What made you choose this path?','Let’s test it somewhere safe first!','That is different from mine. Teach me about it!']},
Killua:{bad:['Seriously? Even Gon might notice that trap.','You are broadcasting your weakness. Stop doing that.','We need an exit plan. Preferably before you charge in.','I know confidence is free. That does not make it useful.'],good:['Nice. You might actually keep up.','That could work. I can already see a few uses.','Now we have an option besides getting punched.','Good. Keep the surprise for the opponent.'],neutral:['What is the catch? There is usually a catch.','I am checking the exits while you explain that.','Interesting. Do not tell every opponent how it works.','Gon wants to try it immediately. I would like some details first.']}
};
const cameos={
fairytail:[['The ship was beside this tavern.','Natsu','Who is the sword guy? Did we recruit someone while I was eating?'],['I followed the smoke.','Natsu','That was my fire! You got lost all the way into our guild?'],['Is this the port?','Lucy','This is a guild hall. Who are you, and why are there THREE swords?'],['I came for the job board.','Lucy','You crossed worlds to find directions and still read the wrong board.']],
mha:[['Is this a training ship?','Deku','Who is he? Three swords, no support license... is getting lost his quirk?'],['The cook sent me this way.','Deku','You crossed into U.A.? I need a whole notebook page for this.'],['Which way is the harbor?','Bakugo','Who let this lost swordsman into the training ground?!'],['The map must be wrong.','Bakugo','The map?! You are in the wrong anime, sword guy!']],
aot:[['The wall was not on my map.','Eren','Who are you? How did you wander through a guarded wall?'],['I am looking for the sea.','Eren','You got lost between worlds and still found a reason to head outside.'],['Are these grapples for a ship?','Mikasa','Who is this man? Those swords are not regulation equipment.'],['I followed the green cloaks.','Mikasa','You are not in our squad. Stay behind the line until we find your way home.']],
hxh:[['Is this the way to the ship?','Gon','Who are you? Are you a Hunter? How did you get here with three swords?'],['I was headed toward an island.','Gon','We should help! Killua, can someone get lost through a whole universe?'],['The sign pointed this way.','Killua','Who is this guy? Your navigation is worse than Gon’s risk assessment.'],['I do not need directions.','Killua','Sure. You only missed your destination by an entire anime.']]
};
// Each entry has original self/partner lines. Aliases are whole-name matches.
const personal={
Yuji:{aliases:['Yuji','Yuji Itadori'],own:['You drew me? I was hoping we could train together instead.','Me as your opponent? I will take this seriously, so get ready.'],partner:['Gojo: Yuji never learned to do anything halfway. Watch his close-range attacks.','Gojo: My student? Good luck. His determination is the exhausting part.']},
Gojo:{aliases:['Gojo','Satoru Gojo'],own:['You drew me. An excellent choice for a very difficult lesson.','Me? Try not to look so nervous. I will grade you generously.'],partner:['Yuji: Gojo is going to enjoy this way too much.','Yuji: Against my teacher? Please tell me we rolled an escape plan.']},
Naruto:{aliases:['Naruto','Naruto Uzumaki'],own:['You are facing me? Bring everything you have!','Me? We can be friends after the match. I am still trying to win.'],partner:['Sasuke: Naruto will keep getting up. Plan for that.','Sasuke: Do not assume the loudest fighter is the easiest to read.']},
Sasuke:{aliases:['Sasuke','Sasuke Uchiha'],own:['You drew me. Show me that your training was worth something.','Facing me? Keep your eyes on the fight, not your reputation.'],partner:['Naruto: Sasuke does not make friendly sparring look very friendly.','Naruto: Watch him carefully. He is already thinking several moves ahead.']},
Luffy:{aliases:['Luffy','Monkey D. Luffy'],own:['You picked me! This is going to be fun!','We are fighting? Okay! There had better be food afterward.'],partner:['Zoro: The captain does not follow neat little plans. Stay adaptable.','Zoro: Against Luffy? Expect something ridiculous that somehow works.']},
Zoro:{aliases:['Zoro','Roronoa Zoro'],own:['Me? Good. Let your training do the talking.','You drew my name. I will find the arena eventually.'],partner:['Luffy: Zoro! The match is over here!','Luffy: You got Zoro! Somebody make sure he reaches the fight.']},
Ichigo:{aliases:['Ichigo','Ichigo Kurosaki'],own:['You drew me? Fine, but let’s keep everyone else out of it.','Against me? I am not backing down if people depend on me.'],partner:['Rukia: He improvises more than he admits. Do not get comfortable.','Rukia: Ichigo is stubborn enough to make your first plan obsolete.']},
Rukia:{aliases:['Rukia','Rukia Kuchiki'],own:['You drew me. I expect proper technique, not excuses.','Me? Watch your footing and pay attention.'],partner:['Ichigo: Take Rukia seriously. Trust me on this one.','Ichigo: She is already deciding which mistake to lecture you about.']},
Goku:{aliases:['Goku','Son Goku'],own:['You get to fight me? Great! Show me your best!','My name came up! I hope you have been training.'],partner:['Vegeta: Kakarot is smiling. That should concern you.','Vegeta: He is already testing your limits. Stop looking impressed.']},
Vegeta:{aliases:['Vegeta'],own:['You drew the prince. Try to make this worth my time.','Me? Good. There will be no excuses when we start.'],partner:['Goku: Vegeta will want your best. He gets cranky about easy fights.','Goku: You are fighting Vegeta? I want to watch this!']},
Natsu:{aliases:['Natsu','Natsu Dragneel'],own:['You drew me! Now I am fired up for a real fight!','Against me? Lucy, keep the mission paperwork away from the flames.'],partner:['Lucy: Natsu, this is a match, not permission to destroy the arena!','Lucy: You drew Natsu. I hope the repair bill is someone else’s problem.']},
Lucy:{aliases:['Lucy','Lucy Heartfilia'],own:['Me? Do not underestimate what my spirits and I can do together.','You drew me. I intend to win with a plan, thank you.'],partner:['Natsu: Lucy has this! Wait, am I supposed to cheer for you too?','Natsu: Do not underestimate Lucy. Her spirits hit hard!']},
Deku:{aliases:['Deku','Izuku','Izuku Midoriya','Midoriya'],own:['You drew me? I have already started analyzing your build. Sorry!','Facing me? I will give it everything, but let’s keep everyone safe.'],partner:['Bakugo: Stop muttering, Deku! They can hear the whole analysis!','Bakugo: The nerd has already filled a notebook about you. Move.']},
Bakugo:{aliases:['Bakugo','Katsuki Bakugo'],own:['You drew me? Then quit staring and get ready to lose!','Me. Good. Now we find out whether your stats mean anything.'],partner:['Deku: Kacchan reads movement incredibly well. Do not rely on one trick.','Deku: His explosions are precise. The shouting is not the whole strategy.']},
Eren:{aliases:['Eren','Eren Yeager','Eren Jaeger'],own:['You drew me. I will not stop just because the odds look bad.','Me as the opponent? Then we both need to know what we are fighting for.'],partner:['Mikasa: Eren commits completely. Watch what that leaves exposed.','Mikasa: Do not provoke him just to see what happens.']},
Mikasa:{aliases:['Mikasa','Mikasa Ackerman'],own:['You drew me. Keep your guard up.','Against me? Check your gear before we begin.'],partner:['Eren: Mikasa is faster than most people expect. Take this seriously.','Eren: Do not wait until she moves to start thinking.']},
Gon:{aliases:['Gon','Gon Freecss'],own:['You drew me! I want to see what your ability can do.','We are opponents? Okay! I will give you everything I have.'],partner:['Killua: Gon is smiling. That means this is about to get reckless.','Killua: He notices things people miss. Do not mistake curiosity for weakness.']},
Killua:{aliases:['Killua','Killua Zoldyck'],own:['You drew me? Try not to give away your whole plan at once.','Me. Interesting. I have already checked your blind spot.'],partner:['Gon: Killua is really fast! You should probably watch both sides.','Gon: He acts casual, but he has already thought about the next move.']}
};
root.AWGReactionExtra={voices,cameos,personal};if(typeof module!=='undefined')module.exports=root.AWGReactionExtra;
})(typeof window!=='undefined'?window:globalThis);
