const assert=require('node:assert/strict'),fs=require('node:fs'),G=require('./game.js'),P=require('./portrait.js'),B=require('./battle.js'),A=require('./battle-art.js');const {setup}=require('./test-mobile.cjs');
for(const gender of ['male','female'])assert.equal(G.fresh('jjk',gender).gender,gender);
assert.equal(G.fresh('jjk','random',()=>0).gender,'male');assert.equal(G.fresh('jjk','random',()=>.99).gender,'female');
const random=G.fresh('jjk','random',()=>.9);assert.equal(G.upgrade(JSON.parse(JSON.stringify(random))).gender,'female');assert.equal(random.genderChoice,'random');
const old=G.fresh('jjk');delete old.gender;delete old.genderChoice;old.finished=true;G.upgrade(old);assert.equal(old.gender,'male');
const ui=setup(false);ui.get('genderChoice').value='female';ui.get('genderChoice').onchange();assert.equal(ui.run('state.gender'),'female');assert.equal(ui.run('prefs.appearance'),'female');assert.equal(ui.run('AWGPortrait.describe(state).gender'),'female');ui.get('spin').click();assert(ui.get('appearanceSetup').hidden);ui.get('genderChoice').value='male';ui.get('genderChoice').onchange();assert.equal(ui.run('state.gender'),'female','Appearance remains stable after starting a run');
let count=0;for(const [world,w] of Object.entries(G.worlds)){assert.deepEqual(B.roster[world],w.enemies);assert(fs.statSync('battle-enemies-'+world+'.png').size>1000);for(const [i,enemy] of w.enemies.entries())for(const outcome of ['VICTORY','DEFEAT'])for(const gender of ['male','female']){const run=G.fresh(world,gender);run.finished=true;run.results=[{id:'enemy',label:enemy},{id:'win',label:outcome},{id:'enemyLevel',label:'Prime'}];const d=B.describe(run);assert.equal(d.enemy,enemy);assert.equal(d.tile,i+(outcome==='VICTORY'?12:0));assert.equal(d.gender,gender);const rect=A[world].frames[d.tile];assert(rect&&rect.length===4,world+' '+enemy+' '+outcome+' has artwork');assert(rect[2]>20&&rect[3]>20);assert(rect[0]>=0&&rect[1]>=0&&rect[0]+rect[2]<=A[world].width&&rect[1]+rect[3]<=A[world].height);assert.deepEqual(B.describe(JSON.parse(JSON.stringify(run))),d);assert.equal(P.describe(run).gender,gender);count++;}}
for(const mobile of [false,true]){const t=setup(mobile);t.run("state=G.fresh('dragonball','female');state.results=[{id:'enemy',label:'Frieza',chapter:5},{id:'origin',label:'Human',chapter:0}];state.index=state.queue.length-1;render()");t.get('spin').click();if(mobile)t.get('continueReaction').click();else t.get('spin').click();assert(t.run('state.finished'));assert(t.get('dialog').open,'Final scene opens automatically');assert.equal(t.get('dialogTitle').textContent,'Your final battle');assert.equal(t.run('archive[0].gender'),'female');assert.equal(t.run('AWGBattle.describe(archive[0]).enemy'),'Frieza');const scene=t.get('dialogBody').children[0];assert(scene.className.includes('player-'));const actions=t.get('dialogBody').children.at(-1);actions.children[0].click();assert(t.get('dialogTitle').textContent.includes('character'));t.run('showCharacter(archive[0])');assert.equal(t.get('dialogTitle').textContent,'Your final battle');t.get('dialogBody').children.at(-1).children[1].click();assert.equal(t.get('dialogTitle').textContent,'Your illustrated character');}
const unknown=G.fresh('jjk');unknown.finished=true;unknown.results=[{id:'enemy',label:'Unknown imported foe'},{id:'win',label:'DEFEAT'}];assert.equal(B.describe(unknown).tile,null,'Never silently substitute a different enemy');assert.equal(B.describe(G.fresh('jjk')),null);
console.log(`v1.3: ${count} enemy/outcome/appearance combinations, stable Random selection, old saves, automatic desktop/mobile reveal, archive replay, stats and clean portrait passed.`);
