const assert=require('node:assert/strict'),fs=require('node:fs'),G=require('./game.js'),P=require('./portrait.js');
const {setup}=require('./test-mobile.cjs');
assert.equal(Object.keys(G.worlds).length,9);
for(const world of Object.keys(G.worlds)){
 const s=G.fresh(world),enemy=s.queue.find(x=>x.id==='enemy');
 for(const name of G.reactionPairs[world]){assert(enemy.options.some(x=>x.label===name),world+' can roll '+name);const r=G.reaction(s,enemy,enemy.options.find(x=>x.label===name),()=>.5);assert.equal(r.recognized,name);for(const who of G.reactionPairs[world])assert(r.text.includes(who+':'));assert(!r.cameo);}
 if(world!=='onepiece')for(let turn=2;turn<4;turn++){s.reactionCount=turn;s.lastZoroCameo=-100;const step=s.queue.find(x=>x.id==='speed');const r=G.reaction(s,step,step.options[0],()=>0);assert(r.cameo);assert.equal(r.cameo.host,G.reactionPairs[world][turn%2]);}
 assert(fs.statSync('reactions-'+world+'.png').size>1000);
}
const aot=G.fresh('aot');const titan=aot.queue.find(s=>s.label==='Titan form');assert.equal(titan.requires,'Titan shifter');
for(const yes of [false,true]){const s=G.fresh('aot');while(!s.finished){const step=G.current(s);s.pending={...step.options[step.label==='Titan shifter'&&yes?1:0]};G.commit(s)}assert.equal(s.results.some(x=>x.name==='Titan form'),yes);assert.equal(s.results.some(x=>x.name==='Titan control'),yes);}
const s=G.fresh('dragonball'),initial=P.describe(s);s.pending={label:'Namekian',score:3};let p=P.describe(s);assert.equal(p.skin,'namekian');assert.equal(p.outfit,8);assert.equal(P.describe(s,false).outfit,null);G.commit(s);s.index=s.queue.findIndex(x=>x.id==='age');s.pending={label:'Ancient',score:3};assert.equal(P.describe(s).base,3);s.pending={label:'16–20',score:3};assert.equal(P.describe(s).base,0);s.pending=null;
s.results.push({id:'exactAge',label:'65'},{id:'faction',label:'Galactic Patrol'},{id:'tool',label:'Sword'},{id:'energy',score:7,label:'Legendary'},{id:'ability1',label:'Disaster Flames'},{id:'mastery1',score:6,label:'Mastered'});p=P.describe(s);assert.equal(p.base,3);assert.equal(p.element,'flame');assert.equal(p.equipment,13);assert.equal(p.intensity,7);assert.equal(p.mastery,6);assert.deepEqual(P.describe(JSON.parse(JSON.stringify(s))),p);const before=JSON.stringify(p);s.results.push({id:'enemy',label:'Frieza'},{id:'enemyLevel',label:'Prime',score:7});assert.equal(JSON.stringify(P.describe(s)),before,'Enemy results cannot alter player portrait');
const ui=setup(false);ui.run("archive=[G.fresh('fairytail'),G.fresh('hxh')];archive[0].id='first';archive[1].id='second';save();showLibrary()");assert.equal(ui.get('dialogBody').children.length,2);ui.run('confirmDelete(archive[0])');let actions=ui.get('dialogBody').children.at(-1);actions.children[0].click();assert.equal(ui.run('archive.length'),2,'Cancel preserves characters');const currentID=ui.run('state.id');ui.run('confirmDelete(archive[0])');ui.get('dialogBody').children.at(-1).children[1].click();assert.equal(ui.run('archive.length'),1);assert.equal(ui.run('archive[0].id'),'second');assert.equal(ui.run('state.id'),currentID);assert.equal(ui.run("JSON.parse(localStorage.getItem(KEY+'-archive'))[0].id"),'second','Deletion persisted');ui.run('const originalWrite=localStorage.setItem;localStorage.setItem=()=>{throw new Error("quota")};confirmDelete(archive[0])');ui.get('dialogBody').children.at(-1).children[1].click();assert.equal(ui.run('archive.length'),1,'Failed write preserves saved character');ui.run('localStorage.setItem=originalWrite');ui.run('confirmDelete(archive[0])');ui.get('dialogBody').children.at(-1).children[1].click();assert.equal(ui.run('archive.length'),0);assert(ui.get('dialogBody').children[0].textContent.includes('Finish a run'));
console.log('v1.2 passed: nine pairs, self-recognition, eight-world Zoro cameos, Titan conditional branches, pending/rerolled/serialized portraits, enemy isolation, deletion cancel/persistence/last item/storage failure.');
