(function(root){
'use strict';
// These are game rules inspired by each world, not a canonical power ranking.
const worlds={
fairytail:{name:'Fairy Tail',energy:'Magic',ability:'Magic spell',origin:['Human mage','Dragon Slayer','Celestial Spirit mage','Exceed','Take Over mage'],clans:['Magnolia','Hargeon','Crocus','Edolas','Alvarez'],groups:['Fairy Tail','Sabertooth','Lamia Scale','Blue Pegasus','Independent'],powers:['Fire Dragon Roar','Celestial Gate','Ice-Make Lance','Requip Armor','Sky Dragon Healing','Lightning Dragon Fist','Solid Script','Water Lock','Take Over','Iron Dragon Spear','Shadow Bind','Fairy Sphere'],enemies:['Wendy','Gray','Lucy','Gajeel','Erza','Natsu','Laxus','Jellal','Zeref','Acnologia'],extras:[['Magic specialty','list',['Fire','Ice-Make','Celestial Spirit','Requip','Sky','Lightning','Iron']],['Guild bond','master'],['Second Origin','bool'],['Second Origin control','master','Second Origin'],['Unison Raid','bool'],['Unison coordination','master','Unison Raid'],['Magic drawback','list',['Long recovery','Heavy fatigue','Short range','Needs a focus']]],weapons:['Celestial keys','Magic staff','Requip sword','Enchanted gauntlets','Whip']},
mha:{name:'My Hero Academia',energy:'Quirk stamina',ability:'Quirk',origin:['Hero student','Pro hero','Vigilante','Villain','Support specialist'],clans:['Musutafu','Hosū','Kamino','Naruhata','Rural hometown'],groups:['U.A. High','Shiketsu High','Hero agency','Independent','League of Villains'],powers:['One For All','Explosion','Zero Gravity','Half-Cold Half-Hot','Hardening','Electrification','Engine','Creation','Dark Shadow','Frog','Erasure','Steel'],enemies:['Mineta','Iida','Uraraka','Kirishima','Todoroki','Deku','Bakugo','Dabi','Shigaraki','All For One'],extras:[['Quirk category','list',['Emitter','Transformation','Mutant']],['Quirk control','master'],['Awakening','bool'],['Awakening mastery','master','Awakening'],['Quirk drawback','list',['Overheating','Stamina drain','Recoil','Limited duration','Needs stored fuel']],['Rescue skill','master'],['Team coordination','master']],weapons:['Support gauntlets','Capture scarf','Armored hero suit','Mobility boots','Utility belt']},
aot:{name:'Attack on Titan',energy:'Endurance',ability:'Combat technique',origin:['Scout recruit','Garrison soldier','Military Police recruit','Warrior candidate','Civilian survivor'],clans:['Shiganshina','Trost','Wall Rose','Liberio','Underground'],groups:['Scout Regiment','Garrison','Military Police','Warrior unit','Independent'],powers:['Nape Strike','Hook Reversal','Blade Feint','Squad Flank','Rapid Ascent','Smoke Diversion','Thunder Spear Volley','Precision Shot','Anchor Pivot','Rescue Grapple','Evasive Roll','Ambush Strike'],enemies:['Pure Titan','Abnormal Titan','Military Police squad','Warrior squad','Jaw Titan','Mikasa','Armored Titan','Eren','Beast Titan','Colossal Titan'],extras:[['Titan shifter','bool'],['Titan form','list',['Attack Titan','Armored Titan','Colossal Titan','Female Titan','Beast Titan','Jaw Titan','Cart Titan','War Hammer Titan','Founding Titan'],'Titan shifter'],['Titan control','master','Titan shifter'],['ODM proficiency','master'],['Gas management','master'],['Squad coordination','master'],['Fortification knowledge','master']],weapons:['ODM blades','Thunder spears','Rifle','Anti-personnel gear','Signal gun']},
hxh:{name:'Hunter × Hunter',energy:'Aura',ability:'Nen ability',origin:['Hunter applicant','Licensed Hunter','Assassin trainee','Martial artist','Chimera Ant'],clans:['Whale Island','Meteor City','Kukuroo Mountain','Yorknew','NGL'],groups:['Hunter Association','Independent','Zoldyck allies','Phantom Troupe','Expedition team'],powers:['Jajanken','Godspeed','Bungee Gum','Chain Jail','Deep Purple','Hakoware','Black Voice','Hide and Seek','Emperor Time','Skill Hunter','Biscuit Training','Dragon Dive'],enemies:['Tonpa','Genthru','Gon','Killua','Knuckle','Feitan','Hisoka','Chrollo','Neferpitou','Meruem'],extras:[['Nen type','list',['Enhancement','Transmutation','Emission','Conjuration','Manipulation','Specialization']],['Ten mastery','master'],['Zetsu mastery','master'],['Ren mastery','master'],['Gyo mastery','master'],['Nen restriction','list',['Time limit','Only against a declared target','Must explain ability','Requires physical contact','Consumes stored aura']],['Restriction discipline','master']],weapons:['Fishing rod','Weighted yo-yos','Chain','Dagger','Staff']}
};
const pairs={fairytail:['Natsu','Lucy'],mha:['Deku','Bakugo'],aot:['Eren','Mikasa'],hxh:['Gon','Killua']};
root.AWGExtra={worlds,pairs};if(typeof module!=='undefined')module.exports=root.AWGExtra;
})(typeof window!=='undefined'?window:globalThis);
